### ISSUE TITLE
Support for Tinkerers Construct Axes

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DuchLord/TreeChopper#20]
Please add support for Tinkerers Construct!

**Comment by DuchLord** [comment]
Hello,

please send me content of your config (.minecraft/config/treechopper.cfg)

**Comment by P3rf3ctXZer0** [comment]
Okay

[treechopper.txt](https://github.com/DuchLord/TreeChopper/files/569227/treechopper.txt)

**Comment by DuchLord** [comment]
I supposed TConstruct hatchet doesn't work, right? That's because you don't allow it. Please add "item.tconstruct.hatchet" into you config. (between allowed axes).
Or just remove your treechopper.cfg from config folder.The mod will automatically generate new one, with newly added axes from last mod update..

**Comment by P3rf3ctXZer0** [comment]
Oh so anytime I add new types of things I should refresh config?

**Comment by DuchLord** [comment]
If you refresh (remove) config, mod will generate new one with default settings.. This "item.tconstruct.hatchet" has been added in a last update.. You were using old one.

If you want to add some new axe or wood, that the mod can work with, use in-game command "/tch printname 1", for print name of target block and hold item. Then just add these names into your config.

**Comment by P3rf3ctXZer0** [comment]
Okay thank you very much; love your mod btw :)
